# Generated by Django 5.1.7 on 2025-07-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0004_author_alter_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='last_nmae',
            new_name='last_name',
        ),
    ]
